-- Aspen Admin UPM schema, aligned with the Node UPM Drizzle model

CREATE TABLE `upm_tenant` (
    `tenant_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_code` VARCHAR(64) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `short_name` VARCHAR(100) NULL,
    `domain` VARCHAR(255) NULL,
    `logo_url` VARCHAR(1000) NULL,
    `locale` VARCHAR(32) NOT NULL DEFAULT 'zh-CN',
    `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `valid_from` DATETIME(3) NULL,
    `valid_to` DATETIME(3) NULL,
    `max_users` INT UNSIGNED NULL,
    `configuration` JSON NULL,
    `version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(64) NULL,
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(64) NULL,
    PRIMARY KEY (`tenant_id`),
    CONSTRAINT `uk_upm_tenant_code` UNIQUE (`tenant_code`),
    CONSTRAINT `uk_upm_tenant_domain` UNIQUE (`domain`),
    INDEX `idx_upm_tenant_status_validity` (`status`, `valid_from`, `valid_to`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_user` (
    `user_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `username` VARCHAR(100) NOT NULL,
    `nickname` VARCHAR(100) NULL,
    `real_name` VARCHAR(100) NULL,
    `user_type` VARCHAR(32) NOT NULL DEFAULT 'member',
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `job_number` VARCHAR(64) NULL,
    `primary_dept_id` BIGINT UNSIGNED NULL,
    `position_title` VARCHAR(100) NULL,
    `avatar_url` VARCHAR(1000) NULL,
    `email` VARCHAR(320) NULL,
    `email_normalized` VARCHAR(320) NULL,
    `email_verified_at` DATETIME(3) NULL,
    `mobile_country_code` VARCHAR(8) NULL,
    `mobile` VARCHAR(32) NULL,
    `mobile_normalized` VARCHAR(32) NULL,
    `mobile_verified_at` DATETIME(3) NULL,
    `gender` VARCHAR(32) NOT NULL DEFAULT 'unknown',
    `locale` VARCHAR(32) NULL,
    `timezone` VARCHAR(64) NULL,
    `source` VARCHAR(32) NOT NULL DEFAULT 'local',
    `external_key` VARCHAR(191) NULL,
    `failed_login_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `locked_until` DATETIME(3) NULL,
    `last_login_at` DATETIME(3) NULL,
    `last_login_ip` VARCHAR(45) NULL,
    `login_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `authorization_version` INT UNSIGNED NOT NULL DEFAULT 1,
    `password_changed_at` DATETIME(3) NULL,
    `must_change_password` BOOLEAN NOT NULL DEFAULT FALSE,
    `valid_from` DATETIME(3) NULL,
    `valid_to` DATETIME(3) NULL,
    `version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(64) NULL,
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(64) NULL,
    PRIMARY KEY (`user_id`),
    CONSTRAINT `fk_upm_user_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `uk_upm_user_tenant_username` UNIQUE (`tenant_id`, `username`),
    CONSTRAINT `uk_upm_user_tenant_job_no` UNIQUE (`tenant_id`, `job_number`),
    CONSTRAINT `uk_upm_user_tenant_email` UNIQUE (`tenant_id`, `email_normalized`),
    CONSTRAINT `uk_upm_user_tenant_mobile` UNIQUE (`tenant_id`, `mobile_normalized`),
    CONSTRAINT `uk_upm_user_tenant_external` UNIQUE (`tenant_id`, `source`, `external_key`),
    INDEX `idx_upm_user_tenant_dept_status` (`tenant_id`, `primary_dept_id`, `status`),
    INDEX `idx_upm_user_tenant_real_name` (`tenant_id`, `real_name`),
    INDEX `idx_upm_user_validity` (`tenant_id`, `valid_from`, `valid_to`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_user_credential` (
    `user_credential_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `credential_type` VARCHAR(32) NOT NULL DEFAULT 'password',
    `secret_hash` VARCHAR(500) NOT NULL,
    `hash_algorithm` VARCHAR(32) NOT NULL,
    `hash_version` VARCHAR(32) NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `expires_at` DATETIME(3) NULL,
    `must_rotate` BOOLEAN NOT NULL DEFAULT FALSE,
    `failed_attempt_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `locked_until` DATETIME(3) NULL,
    `last_used_at` DATETIME(3) NULL,
    `rotated_at` DATETIME(3) NULL,
    `version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(64) NULL,
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(64) NULL,
    PRIMARY KEY (`user_credential_id`),
    CONSTRAINT `fk_upm_credential_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_credential_user` FOREIGN KEY (`user_id`) REFERENCES `upm_user` (`user_id`) ON DELETE CASCADE,
    CONSTRAINT `uk_upm_credential_user_type` UNIQUE (`tenant_id`, `user_id`, `credential_type`),
    INDEX `idx_upm_credential_status_expiry` (`tenant_id`, `status`, `expires_at`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_user_identity` (
    `user_identity_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `provider` VARCHAR(64) NOT NULL,
    `provider_tenant` VARCHAR(191) NOT NULL DEFAULT 'default',
    `subject` VARCHAR(191) NOT NULL,
    `external_username` VARCHAR(191) NULL,
    `profile` JSON NULL,
    `bound_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `last_login_at` DATETIME(3) NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(64) NULL,
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(64) NULL,
    PRIMARY KEY (`user_identity_id`),
    CONSTRAINT `fk_upm_identity_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_identity_user` FOREIGN KEY (`user_id`) REFERENCES `upm_user` (`user_id`) ON DELETE CASCADE,
    CONSTRAINT `uk_upm_identity_provider_subject` UNIQUE (`tenant_id`, `provider`, `provider_tenant`, `subject`),
    CONSTRAINT `uk_upm_identity_user_provider` UNIQUE (`tenant_id`, `user_id`, `provider`, `provider_tenant`),
    INDEX `idx_upm_identity_external_username` (`tenant_id`, `provider`, `external_username`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_dept` (
    `dept_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `parent_id` BIGINT UNSIGNED NULL,
    `dept_code` VARCHAR(64) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `short_name` VARCHAR(100) NULL,
    `full_name` VARCHAR(1000) NULL,
    `dept_type` VARCHAR(32) NOT NULL DEFAULT 'department',
    `ancestor_path` VARCHAR(2000) NOT NULL DEFAULT '/',
    `level` INT UNSIGNED NOT NULL DEFAULT 0,
    `primary_leader_user_id` BIGINT UNSIGNED NULL,
    `is_virtual` BOOLEAN NOT NULL DEFAULT FALSE,
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `sort_order` INT NOT NULL DEFAULT 0,
    `phone` VARCHAR(32) NULL,
    `email` VARCHAR(320) NULL,
    `address` VARCHAR(500) NULL,
    `region_code` VARCHAR(32) NULL,
    `valid_from` DATETIME(3) NULL,
    `valid_to` DATETIME(3) NULL,
    `source` VARCHAR(32) NOT NULL DEFAULT 'local',
    `external_key` VARCHAR(191) NULL,
    `child_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `member_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(64) NULL,
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(64) NULL,
    PRIMARY KEY (`dept_id`),
    CONSTRAINT `fk_upm_dept_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `uk_upm_dept_tenant_code` UNIQUE (`tenant_id`, `dept_code`),
    CONSTRAINT `uk_upm_dept_tenant_external` UNIQUE (`tenant_id`, `source`, `external_key`),
    INDEX `idx_upm_dept_tenant_parent_order` (`tenant_id`, `parent_id`, `sort_order`),
    INDEX `idx_upm_dept_tenant_name` (`tenant_id`, `name`),
    INDEX `idx_upm_dept_leader` (`tenant_id`, `primary_leader_user_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_user_dept` (
    `user_dept_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `dept_id` BIGINT UNSIGNED NOT NULL,
    `is_primary` BOOLEAN NOT NULL DEFAULT FALSE,
    `position_title` VARCHAR(100) NULL,
    `employee_type` VARCHAR(32) NULL,
    `manager_user_id` BIGINT UNSIGNED NULL,
    `joined_at` DATETIME(3) NULL,
    `left_at` DATETIME(3) NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `sort_order` INT NOT NULL DEFAULT 0,
    `version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(64) NULL,
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(64) NULL,
    PRIMARY KEY (`user_dept_id`),
    CONSTRAINT `fk_upm_user_dept_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_user_dept_user` FOREIGN KEY (`user_id`) REFERENCES `upm_user` (`user_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_user_dept_dept` FOREIGN KEY (`dept_id`) REFERENCES `upm_dept` (`dept_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_user_dept_manager` FOREIGN KEY (`manager_user_id`) REFERENCES `upm_user` (`user_id`) ON DELETE SET NULL,
    CONSTRAINT `uk_upm_user_dept_membership` UNIQUE (`tenant_id`, `user_id`, `dept_id`),
    INDEX `idx_upm_user_dept_dept_status` (`tenant_id`, `dept_id`, `status`, `sort_order`),
    INDEX `idx_upm_user_dept_user_primary` (`tenant_id`, `user_id`, `is_primary`),
    INDEX `idx_upm_user_dept_manager` (`tenant_id`, `manager_user_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_dept_closure` (
    `dept_closure_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `ancestor_id` BIGINT UNSIGNED NOT NULL,
    `descendant_id` BIGINT UNSIGNED NOT NULL,
    `depth` INT UNSIGNED NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    PRIMARY KEY (`dept_closure_id`),
    CONSTRAINT `fk_upm_dept_closure_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_dept_closure_ancestor` FOREIGN KEY (`ancestor_id`) REFERENCES `upm_dept` (`dept_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_dept_closure_descendant` FOREIGN KEY (`descendant_id`) REFERENCES `upm_dept` (`dept_id`) ON DELETE CASCADE,
    CONSTRAINT `uk_upm_dept_closure_path` UNIQUE (`tenant_id`, `ancestor_id`, `descendant_id`),
    INDEX `idx_upm_dept_closure_desc_depth` (`tenant_id`, `descendant_id`, `depth`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_dept_leader` (
    `dept_leader_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `dept_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `leader_type` VARCHAR(32) NOT NULL DEFAULT 'primary',
    `valid_from` DATETIME(3) NULL,
    `valid_to` DATETIME(3) NULL,
    `sort_order` INT NOT NULL DEFAULT 0,
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    PRIMARY KEY (`dept_leader_id`),
    CONSTRAINT `fk_upm_dept_leader_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_dept_leader_dept` FOREIGN KEY (`dept_id`) REFERENCES `upm_dept` (`dept_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_dept_leader_user` FOREIGN KEY (`user_id`) REFERENCES `upm_user` (`user_id`) ON DELETE CASCADE,
    CONSTRAINT `uk_upm_dept_leader_type` UNIQUE (`tenant_id`, `dept_id`, `user_id`, `leader_type`),
    INDEX `idx_upm_dept_leader_user` (`tenant_id`, `user_id`, `status`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_password_history` (
    `password_history_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `password_hash` VARCHAR(500) NOT NULL,
    `hash_algorithm` VARCHAR(32) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    PRIMARY KEY (`password_history_id`),
    CONSTRAINT `fk_upm_password_history_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_password_history_user` FOREIGN KEY (`user_id`) REFERENCES `upm_user` (`user_id`) ON DELETE CASCADE,
    INDEX `idx_upm_password_history_user_time` (`user_id`, `created_at`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_role` (
    `role_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `role_code` VARCHAR(64) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `role_type` VARCHAR(32) NOT NULL DEFAULT 'business',
    `owner_dept_id` BIGINT UNSIGNED NULL,
    `data_scope` VARCHAR(32) NOT NULL DEFAULT 'self',
    `is_built_in` BOOLEAN NOT NULL DEFAULT FALSE,
    `is_assignable` BOOLEAN NOT NULL DEFAULT TRUE,
    `priority` INT NOT NULL DEFAULT 0,
    `permission_version` INT UNSIGNED NOT NULL DEFAULT 1,
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `valid_from` DATETIME(3) NULL,
    `valid_to` DATETIME(3) NULL,
    `description` VARCHAR(1000) NULL,
    `version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(64) NULL,
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(64) NULL,
    PRIMARY KEY (`role_id`),
    CONSTRAINT `fk_upm_role_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_role_owner_dept` FOREIGN KEY (`owner_dept_id`) REFERENCES `upm_dept` (`dept_id`) ON DELETE SET NULL,
    CONSTRAINT `uk_upm_role_tenant_code` UNIQUE (`tenant_id`, `role_code`),
    INDEX `idx_upm_role_owner_status` (`tenant_id`, `owner_dept_id`, `status`),
    INDEX `idx_upm_role_type_assignable` (`tenant_id`, `role_type`, `is_assignable`, `status`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_user_role` (
    `user_role_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `role_id` BIGINT UNSIGNED NOT NULL,
    `scope_dept_id` BIGINT UNSIGNED NULL,
    `grant_source` VARCHAR(32) NOT NULL DEFAULT 'manual',
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `valid_from` DATETIME(3) NULL,
    `valid_to` DATETIME(3) NULL,
    `granted_by` BIGINT UNSIGNED NULL,
    `grant_reason` VARCHAR(500) NULL,
    `revoked_at` DATETIME(3) NULL,
    `revoked_by` BIGINT UNSIGNED NULL,
    `revoke_reason` VARCHAR(500) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    PRIMARY KEY (`user_role_id`),
    CONSTRAINT `fk_upm_user_role_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_user_role_user` FOREIGN KEY (`user_id`) REFERENCES `upm_user` (`user_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_user_role_role` FOREIGN KEY (`role_id`) REFERENCES `upm_role` (`role_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_user_role_scope_dept` FOREIGN KEY (`scope_dept_id`) REFERENCES `upm_dept` (`dept_id`) ON DELETE SET NULL,
    CONSTRAINT `fk_upm_user_role_granted_by` FOREIGN KEY (`granted_by`) REFERENCES `upm_user` (`user_id`) ON DELETE SET NULL,
    CONSTRAINT `fk_upm_user_role_revoked_by` FOREIGN KEY (`revoked_by`) REFERENCES `upm_user` (`user_id`) ON DELETE SET NULL,
    CONSTRAINT `uk_upm_user_role_scope` UNIQUE (`tenant_id`, `user_id`, `role_id`, `scope_dept_id`, `grant_source`),
    INDEX `idx_upm_user_role_user_status` (`tenant_id`, `user_id`, `status`, `valid_to`),
    INDEX `idx_upm_user_role_role_status` (`tenant_id`, `role_id`, `status`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_role_dept` (
    `role_dept_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `role_id` BIGINT UNSIGNED NOT NULL,
    `dept_id` BIGINT UNSIGNED NOT NULL,
    `include_children` BOOLEAN NOT NULL DEFAULT TRUE,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    PRIMARY KEY (`role_dept_id`),
    CONSTRAINT `fk_upm_role_dept_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_role_dept_role` FOREIGN KEY (`role_id`) REFERENCES `upm_role` (`role_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_role_dept_dept` FOREIGN KEY (`dept_id`) REFERENCES `upm_dept` (`dept_id`) ON DELETE CASCADE,
    CONSTRAINT `uk_upm_role_dept_scope` UNIQUE (`tenant_id`, `role_id`, `dept_id`),
    INDEX `idx_upm_role_dept_dept` (`tenant_id`, `dept_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_role_inheritance` (
    `role_inheritance_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `parent_role_id` BIGINT UNSIGNED NOT NULL,
    `child_role_id` BIGINT UNSIGNED NOT NULL,
    `depth` INT UNSIGNED NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    PRIMARY KEY (`role_inheritance_id`),
    CONSTRAINT `fk_upm_role_inheritance_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_role_inheritance_parent` FOREIGN KEY (`parent_role_id`) REFERENCES `upm_role` (`role_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_role_inheritance_child` FOREIGN KEY (`child_role_id`) REFERENCES `upm_role` (`role_id`) ON DELETE CASCADE,
    CONSTRAINT `uk_upm_role_inheritance_path` UNIQUE (`tenant_id`, `parent_role_id`, `child_role_id`),
    INDEX `idx_upm_role_inheritance_child` (`tenant_id`, `child_role_id`, `depth`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_menu` (
    `menu_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `parent_id` BIGINT UNSIGNED NULL,
    `menu_code` VARCHAR(100) NOT NULL,
    `platform` VARCHAR(32) NOT NULL DEFAULT 'admin',
    `menu_type` VARCHAR(32) NOT NULL DEFAULT 'page',
    `name` VARCHAR(200) NOT NULL,
    `route_name` VARCHAR(191) NULL,
    `route_path` VARCHAR(500) NULL,
    `component` VARCHAR(500) NULL,
    `redirect` VARCHAR(500) NULL,
    `icon` VARCHAR(191) NULL,
    `active_menu` VARCHAR(191) NULL,
    `external_url` VARCHAR(1000) NULL,
    `open_target` VARCHAR(32) NOT NULL DEFAULT 'self',
    `ancestor_path` VARCHAR(2000) NOT NULL DEFAULT '/',
    `level` INT UNSIGNED NOT NULL DEFAULT 0,
    `is_visible` BOOLEAN NOT NULL DEFAULT TRUE,
    `is_enabled` BOOLEAN NOT NULL DEFAULT TRUE,
    `is_cached` BOOLEAN NOT NULL DEFAULT FALSE,
    `is_affixed` BOOLEAN NOT NULL DEFAULT FALSE,
    `show_breadcrumb` BOOLEAN NOT NULL DEFAULT TRUE,
    `hide_children` BOOLEAN NOT NULL DEFAULT FALSE,
    `sort_order` INT NOT NULL DEFAULT 0,
    `query_parameters` JSON NULL,
    `route_metadata` JSON NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(64) NULL,
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(64) NULL,
    PRIMARY KEY (`menu_id`),
    CONSTRAINT `fk_upm_menu_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `uk_upm_menu_tenant_platform_code` UNIQUE (`tenant_id`, `platform`, `menu_code`),
    INDEX `idx_upm_menu_parent_order` (`tenant_id`, `platform`, `parent_id`, `sort_order`),
    INDEX `idx_upm_menu_route_name` (`tenant_id`, `platform`, `route_name`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_role_menu` (
    `role_menu_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `role_id` BIGINT UNSIGNED NOT NULL,
    `menu_id` BIGINT UNSIGNED NOT NULL,
    `grant_source` VARCHAR(32) NOT NULL DEFAULT 'manual',
    `valid_from` DATETIME(3) NULL,
    `valid_to` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    PRIMARY KEY (`role_menu_id`),
    CONSTRAINT `fk_upm_role_menu_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_role_menu_role` FOREIGN KEY (`role_id`) REFERENCES `upm_role` (`role_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_role_menu_menu` FOREIGN KEY (`menu_id`) REFERENCES `upm_menu` (`menu_id`) ON DELETE CASCADE,
    CONSTRAINT `uk_upm_role_menu_grant` UNIQUE (`tenant_id`, `role_id`, `menu_id`),
    INDEX `idx_upm_role_menu_menu` (`tenant_id`, `menu_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_permission` (
    `permission_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `permission_code` VARCHAR(150) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `permission_type` VARCHAR(32) NOT NULL DEFAULT 'api',
    `resource` VARCHAR(191) NOT NULL,
    `action` VARCHAR(64) NOT NULL,
    `risk_level` VARCHAR(32) NOT NULL DEFAULT 'normal',
    `requires_audit` BOOLEAN NOT NULL DEFAULT FALSE,
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `description` VARCHAR(1000) NULL,
    `version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(64) NULL,
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(64) NULL,
    PRIMARY KEY (`permission_id`),
    CONSTRAINT `fk_upm_permission_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `uk_upm_permission_code` UNIQUE (`tenant_id`, `permission_code`),
    CONSTRAINT `uk_upm_permission_resource_action` UNIQUE (`tenant_id`, `resource`, `action`),
    INDEX `idx_upm_permission_type_status` (`tenant_id`, `permission_type`, `status`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_permission_api` (
    `permission_api_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `permission_id` BIGINT UNSIGNED NOT NULL,
    `application` VARCHAR(64) NOT NULL DEFAULT 'admin-api',
    `http_method` VARCHAR(16) NOT NULL,
    `path_pattern` VARCHAR(500) NOT NULL,
    `api_version` VARCHAR(32) NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    PRIMARY KEY (`permission_api_id`),
    CONSTRAINT `fk_upm_permission_api_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_permission_api_permission` FOREIGN KEY (`permission_id`) REFERENCES `upm_permission` (`permission_id`) ON DELETE CASCADE,
    CONSTRAINT `uk_upm_permission_api_route` UNIQUE (`tenant_id`, `application`, `http_method`, `path_pattern`, `api_version`),
    INDEX `idx_upm_permission_api_permission` (`tenant_id`, `permission_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_role_permission` (
    `role_permission_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `role_id` BIGINT UNSIGNED NOT NULL,
    `permission_id` BIGINT UNSIGNED NOT NULL,
    `grant_source` VARCHAR(32) NOT NULL DEFAULT 'manual',
    `valid_from` DATETIME(3) NULL,
    `valid_to` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    PRIMARY KEY (`role_permission_id`),
    CONSTRAINT `fk_upm_role_permission_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_role_permission_role` FOREIGN KEY (`role_id`) REFERENCES `upm_role` (`role_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_role_permission_permission` FOREIGN KEY (`permission_id`) REFERENCES `upm_permission` (`permission_id`) ON DELETE CASCADE,
    CONSTRAINT `uk_upm_role_permission_grant` UNIQUE (`tenant_id`, `role_id`, `permission_id`),
    INDEX `idx_upm_role_permission_permission` (`tenant_id`, `permission_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_menu_permission` (
    `menu_permission_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `menu_id` BIGINT UNSIGNED NOT NULL,
    `permission_id` BIGINT UNSIGNED NOT NULL,
    `relation_type` VARCHAR(32) NOT NULL DEFAULT 'required',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    PRIMARY KEY (`menu_permission_id`),
    CONSTRAINT `fk_upm_menu_permission_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_menu_permission_menu` FOREIGN KEY (`menu_id`) REFERENCES `upm_menu` (`menu_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_menu_permission_permission` FOREIGN KEY (`permission_id`) REFERENCES `upm_permission` (`permission_id`) ON DELETE CASCADE,
    CONSTRAINT `uk_upm_menu_permission_relation` UNIQUE (`tenant_id`, `menu_id`, `permission_id`),
    INDEX `idx_upm_menu_permission_permission` (`tenant_id`, `permission_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_user_permission` (
    `user_permission_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `permission_id` BIGINT UNSIGNED NOT NULL,
    `effect` VARCHAR(16) NOT NULL DEFAULT 'allow',
    `valid_from` DATETIME(3) NULL,
    `valid_to` DATETIME(3) NULL,
    `reason` VARCHAR(500) NULL,
    `granted_by` BIGINT UNSIGNED NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    PRIMARY KEY (`user_permission_id`),
    CONSTRAINT `fk_upm_user_permission_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_user_permission_user` FOREIGN KEY (`user_id`) REFERENCES `upm_user` (`user_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_user_permission_permission` FOREIGN KEY (`permission_id`) REFERENCES `upm_permission` (`permission_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_user_permission_granted_by` FOREIGN KEY (`granted_by`) REFERENCES `upm_user` (`user_id`) ON DELETE SET NULL,
    CONSTRAINT `uk_upm_user_permission_effect` UNIQUE (`tenant_id`, `user_id`, `permission_id`, `effect`),
    INDEX `idx_upm_user_permission_active` (`tenant_id`, `user_id`, `valid_from`, `valid_to`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_user_session` (
    `user_session_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `session_id` VARCHAR(191) NOT NULL,
    `refresh_token_hash` VARCHAR(500) NOT NULL,
    `device_id` VARCHAR(191) NULL,
    `client_name` VARCHAR(100) NULL,
    `client_version` VARCHAR(64) NULL,
    `ip_address` VARCHAR(45) NULL,
    `user_agent` VARCHAR(1000) NULL,
    `last_active_at` DATETIME(3) NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `revoked_at` DATETIME(3) NULL,
    `revoked_by` BIGINT UNSIGNED NULL,
    `revoke_reason` VARCHAR(500) NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(64) NULL,
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(64) NULL,
    PRIMARY KEY (`user_session_id`),
    CONSTRAINT `fk_upm_user_session_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_user_session_user` FOREIGN KEY (`user_id`) REFERENCES `upm_user` (`user_id`) ON DELETE CASCADE,
    CONSTRAINT `fk_upm_user_session_revoked_by` FOREIGN KEY (`revoked_by`) REFERENCES `upm_user` (`user_id`) ON DELETE SET NULL,
    CONSTRAINT `uk_upm_user_session_id` UNIQUE (`tenant_id`, `session_id`),
    CONSTRAINT `uk_upm_user_session_refresh_hash` UNIQUE (`tenant_id`, `refresh_token_hash`),
    INDEX `idx_upm_user_session_user_active` (`tenant_id`, `user_id`, `status`, `expires_at`),
    INDEX `idx_upm_user_session_expiry` (`tenant_id`, `expires_at`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_user_mfa` (
    `user_mfa_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `mfa_type` VARCHAR(32) NOT NULL,
    `encrypted_secret` VARCHAR(1000) NULL,
    `credential_id` VARCHAR(500) NULL,
    `is_primary` BOOLEAN NOT NULL DEFAULT FALSE,
    `verified_at` DATETIME(3) NULL,
    `last_used_at` DATETIME(3) NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
    `version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(64) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(64) NULL,
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(64) NULL,
    PRIMARY KEY (`user_mfa_id`),
    CONSTRAINT `fk_upm_user_mfa_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_upm_user_mfa_user` FOREIGN KEY (`user_id`) REFERENCES `upm_user` (`user_id`) ON DELETE CASCADE,
    CONSTRAINT `uk_upm_user_mfa_credential` UNIQUE (`tenant_id`, `credential_id`),
    INDEX `idx_upm_user_mfa_user_primary` (`tenant_id`, `user_id`, `is_primary`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_login_log` (
    `login_log_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NULL,
    `username_snapshot` VARCHAR(191) NULL,
    `identity_provider` VARCHAR(64) NULL,
    `result` VARCHAR(32) NOT NULL,
    `failure_code` VARCHAR(64) NULL,
    `failure_message` VARCHAR(500) NULL,
    `ip_address` VARCHAR(45) NULL,
    `user_agent` VARCHAR(1000) NULL,
    `device_id` VARCHAR(191) NULL,
    `request_id` VARCHAR(191) NULL,
    `session_id` VARCHAR(191) NULL,
    `occurred_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `context` JSON NULL,
    PRIMARY KEY (`login_log_id`),
    CONSTRAINT `fk_upm_login_log_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    INDEX `idx_upm_login_log_tenant_time` (`tenant_id`, `occurred_at`),
    INDEX `idx_upm_login_log_user_time` (`tenant_id`, `user_id`, `occurred_at`),
    INDEX `idx_upm_login_log_result_time` (`tenant_id`, `result`, `occurred_at`),
    INDEX `idx_upm_login_log_ip_time` (`tenant_id`, `ip_address`, `occurred_at`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `upm_authorization_change_log` (
    `authorization_change_log_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL,
    `operator_user_id` BIGINT UNSIGNED NULL,
    `subject_type` VARCHAR(32) NOT NULL,
    `subject_id` BIGINT UNSIGNED NOT NULL,
    `action` VARCHAR(64) NOT NULL,
    `before_snapshot` JSON NULL,
    `after_snapshot` JSON NULL,
    `reason` VARCHAR(500) NULL,
    `request_id` VARCHAR(191) NULL,
    `ip_address` VARCHAR(45) NULL,
    `occurred_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`authorization_change_log_id`),
    CONSTRAINT `fk_upm_authz_log_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `upm_tenant` (`tenant_id`) ON DELETE RESTRICT,
    INDEX `idx_upm_authz_log_subject_time` (`tenant_id`, `subject_type`, `subject_id`, `occurred_at`),
    INDEX `idx_upm_authz_log_operator_time` (`tenant_id`, `operator_user_id`, `occurred_at`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
